const portfolio = 'https://yutongchenlailai.github.io/yutong-portfolio/';
export const nodes = [
  {id:'poopslaves',category:'my-work',categoryLabel:'MY WORK',title:'PoopSlaves / Excremental Economy',image:'/images/poopslaves.jpg',radius:72,x:.50,y:.24,keywords:['Body','System','Agency'],reflection:'A speculative VR system that makes artificial rules physically felt. It was where I began treating interaction as a way to interfere with perception and judgement.',url:`${portfolio}#project/poopslaves`},
  {id:'plantievers',category:'my-work',categoryLabel:'MY WORK',title:'Unsettling the Auspicious Pine',image:'/images/plantievers.jpg',radius:72,x:.38,y:.41,keywords:['Body','Culture','Interpretation'],reflection:'A moving-image project that reworks a familiar cultural symbol through digital mediation, making me interested in how representations can destabilise what we think we already understand.',url:`${portfolio}#project/plantievers-illusion`},
  {id:'human-ai',category:'my-work',categoryLabel:'MY WORK',title:'Contextual Triangle / Codex Prototype',image:'/images/human-ai.jpg',radius:72,x:.62,y:.41,keywords:['System','Agency','Creation'],newSinceIED:true,reflection:'I built this interface with a code-generation system while asking where ideas, decisions and authorship come from when AI participates in making.',url:portfolio},
  {id:'skiing',category:'outside',categoryLabel:'THINGS I FIND INTERESTING',title:'Skiing',image:'/images/skiing.jpg',radius:72,x:.29,y:.65,keywords:['Body','Speed','Decision'],reflection:'Decisions happen before they can become fully verbal. Speed, balance, fear, terrain and previous movement all affect what I do next.',url:'https://youtu.be/Ugtvrenz0Kc'},
  {id:'qingtian-puppy',category:'outside',categoryLabel:'THINGS I FIND INTERESTING',title:'Sunny Puppy / 晴天小狗',image:'/images/qingtian-puppy.jpg',radius:72,x:.39,y:.70,keywords:['CUTE 3D MODELLING','VIRTUAL PET','AFFECT','ATTACHMENT'],reflection:'I am interested in its baby-like 3D character modelling and how a virtual pet can create emotional attachment.',reflectionCN:'我喜欢《晴天小狗》里幼态、圆润的小狗建模，以及虚拟角色如何让人产生情感连接。',url:''},
  {id:'zheng-bo',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Zheng Bo — Pteridophilia',image:'/images/zheng-bo.jpg',radius:72,x:.58,y:.60,keywords:['Body','Ecology','Agency'],reflection:'I wish I had made this because it constructs a situation in which the body has to negotiate an idea instead of simply being told what it means.',url:'https://zhengbo.org/'},
  {id:'yang-fudong',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Yang Fudong — The Fifth Night',image:'/images/yang-fudong.jpg',radius:72,x:.70,y:.66,keywords:['Perception','Ambiguity','Interpretation'],reflection:'A single event becomes unstable when distributed across multiple viewpoints. The viewer has to decide where to look and how to construct meaning.',url:'https://www.sifang.art/yang-fudong'},
  {id:'li-yi-fan',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Li Yi-Fan — Screen Melancholy',image:'/images/li-yifan.jpg',radius:72,x:.72,y:.48,keywords:['System','Tool','Agency'],reflection:'The tool becomes visible inside the work: the artist is simultaneously author, operator and subject of a technical system.',url:'https://www.instagram.com/liyifanyifanli/'},
  {id:'ray-lc',category:'outside',categoryLabel:'THINGS I FIND INTERESTING',title:'RAY LC / 羅鋭',image:'/images/ray-lc.jpg',radius:72,x:.37,y:.67,keywords:['HCI','Human–AI Collaboration','Interaction'],descriptionEN:'Designing interactions where computation becomes a collaborator rather than a hidden tool.',url:'https://raylc.org/'}
];
export const relations = [
  {source:'poopslaves',target:'li-yi-fan',strength:.8,label:'SYSTEM / TOOL / AGENCY'},{source:'poopslaves',target:'human-ai',strength:.65,label:'SYSTEM / AGENCY'},{source:'plantievers',target:'yang-fudong',strength:.9,label:'CULTURE / INTERPRETATION / AMBIGUITY'},{source:'plantievers',target:'zheng-bo',strength:.7,label:'BODY / CULTURE / AGENCY'},{source:'li-yi-fan',target:'human-ai',strength:1,label:'SOFTWARE / CO-CREATION / CREATIVE AGENCY'},{source:'skiing',target:'human-ai',strength:.55,label:'PERCEPTION / FEEDBACK / ADAPTATION'},{source:'ray-lc',target:'human-ai',strength:.95,label:'HCI / HUMAN–AI / COLLABORATION'},{source:'ray-lc',target:'skiing',strength:.55,label:'EMBODIMENT / INTERACTION'},{source:'qingtian-puppy',target:'human-ai',strength:.75,label:'AFFECT / DIGITAL COMPANION / INTERACTION'},{source:'qingtian-puppy',target:'poopslaves',strength:.55,label:'3D WORLD / EMBODIED INTERACTION'},{source:'qingtian-puppy',target:'li-yi-fan',strength:.5,label:'DIGITAL FORM / SOFTWARE / VISUAL LANGUAGE'}
];
