const portfolio = 'https://yutongchenlailai.github.io/yutong-portfolio/';
export const nodes = [
  {id:'poopslaves',category:'my-work',categoryLabel:'MY WORK',title:'PoopSlaves',image:'/images/poopslaves.jpg',radius:25,x:.50,y:.30,keywords:['Scarcity','Rules','Real-time Feedback','Agency'],descriptionEN:'A rule-based VR economy using real-time feedback to explore how systems shape choice and behaviour.',url:`${portfolio}#project/poopslaves`},
  {id:'plantievers',category:'my-work',categoryLabel:'MY WORK',title:'Plantiever’s Illusion',image:'/images/plantievers.jpg',radius:24,x:.38,y:.43,keywords:['Culture','Embodiment','Interpretation','Power'],descriptionEN:'An embodied moving-image work exploring how cultural constraints shape perception, behaviour and interpretation.',url:`${portfolio}#project/plantievers-illusion`},
  {id:'human-ai',category:'my-work',categoryLabel:'MY WORK',title:'Human–AI Experiment',image:'/images/human-ai.jpg',radius:24,x:.62,y:.43,keywords:['Co-creation','Ideation','Iteration','Agency'],descriptionEN:'Exploring how AI changes ideation, iteration and the creator’s sense of agency.',url:portfolio},
  {id:'skiing',category:'outside',categoryLabel:'THINGS I FIND INTERESTING',title:'Skiing',image:'/images/skiing.jpg',radius:22,x:.32,y:.65,keywords:['Embodiment','Perception','Feedback','Adaptation'],descriptionEN:'The body continuously senses terrain, decides, acts and adapts through feedback.',url:'',qrImage:'/images/douyin-qr.jpg'},
  {id:'zheng-bo',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Zheng Bo / 郑波',image:'/images/zheng-bo.jpg',radius:23,x:.62,y:.61,keywords:['Agency','Ecology','More-than-human'],descriptionEN:'Humans are not the only agents within a system.',url:'https://zhengbo.org/'},
  {id:'yang-fudong',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Yang Fudong / 杨福东',image:'/images/yang-fudong.jpg',radius:23,x:.73,y:.69,keywords:['Ambiguity','Interpretation','Cultural Memory'],descriptionEN:'Meaning does not need to be fixed; ambiguity can create space for interpretation.',url:'https://www.sifang.art/yang-fudong'},
  {id:'li-yi-fan',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'Li Yi-Fan / 李亦凡',image:'/images/li-yifan.jpg',radius:23,x:.76,y:.49,keywords:['Software','Digital Image','Creative Agency'],descriptionEN:'Software is not neutral; it also shapes the creative process.',url:'https://www.li-yifan.com/'},
  {id:'ray-lc',category:'references',categoryLabel:"WORK OF OTHERS I WISH I'D MADE",title:'RAY LC / 羅鋭',image:'/images/ray-lc.jpg',radius:23,x:.66,y:.75,keywords:['HCI','Human–AI Collaboration','Interaction'],descriptionEN:'Designing interactions where computation becomes a collaborator rather than a hidden tool.',url:'https://raylc.org/'}
];
export const relations = [
  {source:'poopslaves',target:'li-yi-fan',strength:.8,label:'SYSTEM / TOOL'},{source:'poopslaves',target:'human-ai',strength:.65,label:'SYSTEM / AGENCY'},{source:'plantievers',target:'yang-fudong',strength:.9,label:'CULTURE / INTERPRETATION'},{source:'plantievers',target:'zheng-bo',strength:.7,label:'BODY / AGENCY'},{source:'li-yi-fan',target:'human-ai',strength:1,label:'SOFTWARE / CREATIVE AGENCY'},{source:'skiing',target:'human-ai',strength:.55,label:'PERCEPTION / FEEDBACK'},{source:'ray-lc',target:'human-ai',strength:.95,label:'HCI / HUMAN–AI COLLABORATION'},{source:'ray-lc',target:'skiing',strength:.55,label:'EMBODIMENT / INTERACTION'}
];
