import './style.css';
import { nodes, relations } from './data.js';

const canvas = document.querySelector('#triangle'), ctx = canvas.getContext('2d');
const detail = document.querySelector('#detail'), modeButton = document.querySelector('#mode');
const images = new Map(), field = document.createElement('canvas'), fctx = field.getContext('2d');
const TAU = Math.PI * 2, GAP = 5;
let W, H, dpr, fw, fh, mode = 'night', hovered = null, drag = null, selected = [];
modeButton.addEventListener('click', () => { mode = mode === 'night' ? 'day' : 'night'; document.body.classList.toggle('day', mode === 'day'); modeButton.textContent = mode === 'day' ? 'NIGHT MODE' : 'DAY MODE'; });
const asset = path => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;
for (const n of nodes) { n.home = { x: n.x, y: n.y }; n.vx = 0; n.vy = 0; const image = new Image(); image.onload = () => images.set(n.id, image); image.src = asset(n.image); }
function resize() { dpr = devicePixelRatio || 1; W = innerWidth; H = innerHeight; canvas.width = W * dpr; canvas.height = H * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); fw = Math.floor(W / 2); fh = Math.floor(H / 2); field.width = fw; field.height = fh; }
function tri() { const s = Math.min(W, H * 1.06), cx = W * .52, top = H * .15, base = top + s * .74; return [{x:cx,y:top},{x:cx-s*.43,y:base},{x:cx+s*.43,y:base}]; }
function pos(n) { return { x: n.x * W, y: n.y * H }; }
function radiusOf(n) { return Math.max(28, 48 * Math.min(W, H) / 900) * (selected.includes(n) ? 1.05 : 1); }
function constrain(n) { const t = tri(), p = pos(n), r = radiusOf(n) + GAP, center = t.reduce((q,v)=>({x:q.x+v.x/3,y:q.y+v.y/3}),{x:0,y:0}); for (let pass=0; pass<4; pass++) for (let i=0;i<3;i++) { const a=t[i], b=t[(i+1)%3], dx=b.x-a.x, dy=b.y-a.y, len=Math.hypot(dx,dy), cross=dx*(p.y-a.y)-dy*(p.x-a.x), orientation=dx*(center.y-a.y)-dy*(center.x-a.x), d=orientation>=0?cross/len:-cross/len, nx=orientation>=0?-dy/len:dy/len, ny=orientation>=0?dx/len:-dx/len; if (d < r) { p.x += nx*(r-d); p.y += ny*(r-d); } } n.x=Math.max(0,Math.min(1,p.x/W)); n.y=Math.max(0,Math.min(1,p.y/H)); }
function separateNodes() { for (let pass=0;pass<2;pass++) for(let i=0;i<nodes.length;i++) for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],pa=pos(a),pb=pos(b),dx=pb.x-pa.x,dy=pb.y-pa.y,d=Math.hypot(dx,dy)||1,min=radiusOf(a)+radiusOf(b)+8;if(d<min){const q=(min-d)/d/2,ax=dx*q/W,ay=dy*q/H;if(a!==drag?.node){a.x-=ax;a.y-=ay}if(b!==drag?.node){b.x+=ax;b.y+=ay}constrain(a);constrain(b)}} }
function relation(a,b) { return relations.find(r => (r.source===a.id&&r.target===b.id)||(r.source===b.id&&r.target===a.id)); }
function openNode(n) { if (n.url) window.open(n.url,'_blank','noopener,noreferrer'); }
function select(n) { if (!n) selected=[]; else if (selected.includes(n)) selected=selected.filter(x=>x!==n); else selected=selected.length===2?[selected[1],n]:[...selected,n]; renderDetail(); }
function renderDetail() { if (!selected.length) { detail.className=''; detail.innerHTML=''; return; } if(selected.length===2){ const r=relation(selected[0],selected[1]); detail.className=r?'visible relation-detail':''; detail.innerHTML=r?`<span>RELATIONSHIP / 关系</span><h2>${r.label}</h2><small>${selected[0].title} ↔ ${selected[1].title}</small>`:''; return; } const n=selected[0]; detail.className='visible'; detail.innerHTML=`<span>${n.categoryLabel}${n.newSinceIED?' · NEW SINCE IED':''}</span><h2>${n.title}</h2><div class="keywords">${n.keywords.join(' · ')}</div><p>${n.reflection||n.descriptionEN||''}</p>${n.reflectionCN?`<small>${n.reflectionCN}</small>`:''}<button class="open">OPEN ↗</button>`; detail.querySelector('.open').onclick=()=>openNode(n); }
function blobCircle(n,x,y,r) { const image=images.get(n.id);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.clip();if(image){const s=Math.max(r*2/image.width,r*2/image.height);ctx.drawImage(image,x-image.width*s/2,y-image.height*s/2,image.width*s,image.height*s);ctx.fillStyle='rgba(0,0,0,.16)';ctx.fillRect(x-r,y-r,r*2,r*2)}else{ctx.fillStyle='#181818';ctx.fillRect(x-r,y-r,r*2,r*2);ctx.fillStyle='#888';ctx.font='8px Space Mono';ctx.textAlign='center';ctx.fillText('IMAGE',x,y+3)}ctx.restore();ctx.strokeStyle=selected.includes(n)?'#fff':'rgba(255,255,255,.5)';ctx.lineWidth=selected.includes(n)?1.5:1;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.stroke();}
function drawCallout() { if(selected.length!==2||!relation(selected[0],selected[1]))return;const a=pos(selected[0]),b=pos(selected[1]),r=relation(selected[0],selected[1]),start={x:(a.x+b.x)/2,y:(a.y+b.y)/2};const side=start.x<W*.42?'left':start.x>W*.68?'right':'top',end=side==='left'?{x:W*.07,y:H*.47}:side==='right'?{x:W*.91,y:H*.47}:{x:W*.55,y:H*.055},c1={x:(start.x+end.x)/2,y:(start.y+end.y)/2-70},c2={x:(start.x+end.x)/2,y:(start.y+end.y)/2+70};ctx.save();ctx.strokeStyle=mode==='day'?'#222':'#eee';ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.bezierCurveTo(c1.x,c1.y,c2.x,c2.y,end.x,end.y);ctx.stroke();ctx.setLineDash([]);ctx.font='11px Space Mono';ctx.fillStyle=ctx.strokeStyle;ctx.fillText(r.label.split(' / ').join('   '),end.x,end.y);ctx.restore();}
function drawLiquidLayer(){const linked=new Set();for(const r of relations){const a=nodes.find(n=>n.id===r.source),b=nodes.find(n=>n.id===r.target);if(!a||!b)continue;const pa=pos(a),pb=pos(b);if(Math.hypot(pb.x-pa.x,pb.y-pa.y)<(radiusOf(a)+radiusOf(b))*2.6){linked.add(a);linked.add(b)}}if(!linked.size)return;const data=fctx.createImageData(fw,fh),px=data.data;for(let y=0;y<fh;y++)for(let x=0;x<fw;x++){let v=0;for(const n of linked){const p=pos(n),r=radiusOf(n)*1.18,dx=x*2-p.x,dy=y*2-p.y;v+=r*r/Math.max(1,dx*dx+dy*dy)}if(v>.58){const i=(y*fw+x)*4,c=mode==='day'?0:245;px[i]=px[i+1]=px[i+2]=c;px[i+3]=Math.min(235,155+v*70)}}fctx.putImageData(data,0,0);ctx.save();ctx.globalAlpha=.9;ctx.drawImage(field,0,0,W,H);ctx.restore();}
function draw(){ctx.clearRect(0,0,W,H);const t=tri();ctx.strokeStyle=mode==='day'?'#111':'#eee';ctx.lineWidth=Math.max(1,Math.min(W,H)/700);ctx.beginPath();t.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.fillStyle=mode==='day'?'#555':'#666';ctx.font=`${Math.max(8,Math.min(W,H)/100)}px Space Mono`;ctx.fillText('MY WORK',t[0].x-28,t[0].y-34);ctx.fillText('THINGS I FIND INTERESTING',t[1].x-18,t[1].y+42);ctx.fillText("WORK OF OTHERS I WISH I'D MADE",t[2].x-130,t[2].y+42);for(const n of nodes){let tx=n.home.x,ty=n.home.y;if(selected.length&&selected[0]!==n){const r=relation(selected[0],n);if(r){tx=selected[0].x+(n.home.x-selected[0].x)*(1-r.strength*.55);ty=selected[0].y+(n.home.y-selected[0].y)*(1-r.strength*.55)}}n.vx=(n.vx+(tx-n.x)*.06)*.82;n.vy=(n.vy+(ty-n.y)*.06)*.82;n.x+=n.vx;n.y+=n.vy;constrain(n)}separateNodes();drawLiquidLayer();drawCallout();for(const n of nodes){const p=pos(n);blobCircle(n,p.x,p.y,radiusOf(n))}requestAnimationFrame(draw)}
function hit(x,y){return nodes.find(n=>{const p=pos(n);return Math.hypot(x-p.x,y-p.y)<radiusOf(n)})}
canvas.addEventListener('pointermove',e=>{hovered=hit(e.clientX,e.clientY);if(!drag)return;drag.node.x+=(e.clientX-drag.lastX)/W;drag.node.y+=(e.clientY-drag.lastY)/H;drag.node.vx=drag.node.vy=0;constrain(drag.node);drag.lastX=e.clientX;drag.lastY=e.clientY;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>7)drag.moved=true});
canvas.addEventListener('pointerdown',e=>{const n=hit(e.clientX,e.clientY);if(!n){select(null);return}drag={node:n,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointerup',()=>{if(!drag)return;const d=drag;drag=null;if(!d.moved)select(d.node)});canvas.addEventListener('pointercancel',()=>drag=null);addEventListener('keydown',e=>{if(e.key==='Escape')select(null)});addEventListener('resize',resize);resize();draw();
