import './style.css';
import { nodes, relations } from './data.js';

const canvas=document.querySelector('#triangle'),ctx=canvas.getContext('2d'),detail=document.querySelector('#detail');
const images=new Map(),field=document.createElement('canvas'),fctx=field.getContext('2d'),TAU=Math.PI*2,GAP=8;let W,H,dpr,selected=null,drag=null;
const keywordCloud=[...document.querySelectorAll('.keyword')];
const asset=p=>`${import.meta.env.BASE_URL}${p.replace(/^\//,'')}`;
for(const n of nodes){n.vx=0;n.vy=0;const image=new Image();image.onload=()=>images.set(n.id,image);image.src=asset(n.image)}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);field.width=Math.floor(W*dpr);field.height=Math.floor(H*dpr);fctx.imageSmoothingEnabled=true;layout()}
function tri(){const s=Math.min(W,H*1.06),cx=W*.52,top=H*.15,base=top+s*.64;return[{x:cx,y:top},{x:cx-s*.48,y:base},{x:cx+s*.48,y:base}]}
function radiusOf(n){return Math.max(28,48*Math.min(W,H)/900)*(n===selected?1.05:1)}
function relation(a,b){return relations.find(r=>(r.source===a.id&&r.target===b.id)||(r.source===b.id&&r.target===a.id))}
function layout(){if(!W)return;const[t,l,r]=tri(),R=radiusOf(nodes[0]),groups={"my-work":[nodes.filter(n=>n.category==='my-work'),[[0,2],[-1,3.732],[1,3.732]]],outside:[nodes.filter(n=>n.category==='outside'),[[2,-2],[3.732,-1],[3.732,1]]],references:[nodes.filter(n=>n.category==='references'),[[-2,-2],[-3.732,-1],[-3.732,1],[-5.464,0]]]};for(const[key,[list,offsets]]of Object.entries(groups)){const anchor=key==='my-work'?t:key==='outside'?l:r;list.forEach((n,i)=>{const o=offsets[i]||[0,i+2];n.x=(anchor.x+o[0]*R)/W;n.y=(anchor.y+o[1]*R)/H;constrain(n)});for(let pass=0;pass<36;pass++){for(const n of list)constrain(n);for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],pa={x:a.x*W,y:a.y*H},pb={x:b.x*W,y:b.y*H},dx=pb.x-pa.x,dy=pb.y-pa.y,d=Math.hypot(dx,dy)||1,target=radiusOf(a)+radiusOf(b),q=(target-d)/d/2;if(Math.abs(target-d)>.15){a.x-=dx*q/W;a.y-=dy*q/H;b.x+=dx*q/W;b.y+=dy*q/H}}}for(const n of list){constrain(n);n.home={x:n.x,y:n.y}}}}
function constrain(n){const t=tri(),p={x:n.x*W,y:n.y*H},center=t.reduce((q,v)=>({x:q.x+v.x/3,y:q.y+v.y/3}),{x:0,y:0}),r0=radiusOf(n)+GAP;for(let pass=0;pass<4;pass++)for(let i=0;i<3;i++){const a=t[i],b=t[(i+1)%3],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),cross=dx*(p.y-a.y)-dy*(p.x-a.x),ori=dx*(center.y-a.y)-dy*(center.x-a.x),d=ori>=0?cross/len:-cross/len,nx=ori>=0?-dy/len:dy/len,ny=ori>=0?dx/len:-dx/len;if(d<r0){p.x+=nx*(r0-d);p.y+=ny*(r0-d)}}n.x=p.x/W;n.y=p.y/H}
function related(n){return nodes.filter(x=>x!==n&&relation(n,x))}
function openNode(n){if(n.url)window.open(n.url,'_blank','noopener,noreferrer')}
function select(n){selected=n;keywordCloud.forEach(k=>k.classList.toggle('active',!!n&&n.dataset.keys.split(' ').some(word=>n.keywords.some(value=>value.toLowerCase().includes(word.toLowerCase())))));if(!n){detail.className='';detail.innerHTML='';return}detail.className='visible';detail.innerHTML=`<span>${n.categoryLabel}${n.newSinceIED?' · NEW SINCE IED':''}</span><h2>${n.title}</h2><div class="keywords">${n.keywords.join(' · ')}</div><p>${n.reflection||n.descriptionEN||''}</p>${n.reflectionCN?`<small>${n.reflectionCN}</small>`:''}<button class="open">OPEN ↗</button>`;detail.querySelector('.open').onclick=()=>openNode(n)}
function blob(n,x,y,r){const image=images.get(n.id);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.clip();if(image){const s=Math.max(r*2/image.width,r*2/image.height);ctx.drawImage(image,x-image.width*s/2,y-image.height*s/2,image.width*s,image.height*s)}else{ctx.fillStyle='#181818';ctx.fillRect(x-r,y-r,r*2,r*2);ctx.fillStyle='#888';ctx.font='8px Space Mono';ctx.textAlign='center';ctx.fillText('IMAGE',x,y+3)}ctx.restore();ctx.strokeStyle=n===selected?'#fff':'rgba(255,255,255,.5)';ctx.lineWidth=n===selected?1.5:1;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.stroke()}
function drawFusion(){if(!selected)return;const linked=[selected,...related(selected)],data=fctx.createImageData(field.width,field.height),px=data.data,scale=field.width/W;for(let y=0;y<field.height;y++)for(let x=0;x<field.width;x++){const sx=x/scale,sy=y/scale;let value=0;for(const n of linked){const p={x:n.x*W,y:n.y*H},r=radiusOf(n)*1.42,dx=sx-p.x,dy=sy-p.y;value+=r*r/Math.max(1,dx*dx+dy*dy)}if(value>.62){const i=(y*field.width+x)*4;px[i]=px[i+1]=px[i+2]=245;px[i+3]=Math.min(235,145+value*80)}}fctx.putImageData(data,0,0);ctx.save();ctx.globalAlpha=.95;ctx.drawImage(field,0,0,W,H);ctx.restore()}
function separateRelated(){if(!selected)return;const group=[selected,...related(selected)];for(let pass=0;pass<3;pass++)for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++){const a=group[i],b=group[j],pa={x:a.x*W,y:a.y*H},pb={x:b.x*W,y:b.y*H},dx=pb.x-pa.x,dy=pb.y-pa.y,d=Math.hypot(dx,dy)||1,min=radiusOf(a)+radiusOf(b)+6;if(d<min){const q=(min-d)/d/2;if(a!==selected){a.x-=dx*q/W;a.y-=dy*q/H}if(b!==selected){b.x+=dx*q/W;b.y+=dy*q/H}constrain(a);constrain(b)}}}
function separateAll(){for(let pass=0;pass<4;pass++)for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],pa={x:a.x*W,y:a.y*H},pb={x:b.x*W,y:b.y*H},dx=pb.x-pa.x,dy=pb.y-pa.y,d=Math.hypot(dx,dy)||1,min=radiusOf(a)+radiusOf(b)+6;if(d<min){const q=(min-d)/d/2;if(a!==selected){a.x-=dx*q/W;a.y-=dy*q/H}if(b!==selected){b.x+=dx*q/W;b.y+=dy*q/H}constrain(a);constrain(b)}}}
function bridge(a,b){const pa={x:a.x*W,y:a.y*H},pb={x:b.x*W,y:b.y*H},ra=radiusOf(a),rb=radiusOf(b),dx=pb.x-pa.x,dy=pb.y-pa.y,d=Math.hypot(dx,dy)||1,threshold=5*((ra+rb)/2);if(d>=threshold)return;const strength=Math.max(0,Math.min(1,(threshold-d)/(threshold-((ra+rb)/2)*1.2))),lobeA=ra*(1.28+strength*.42),lobeB=rb*(1.28+strength*.42),width=Math.max(ra*1.25,Math.min(ra*2.8,ra*1.25+strength*ra*1.55)),ink='#f5f5f2';ctx.save();ctx.fillStyle=ink;ctx.strokeStyle=ink;ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(pa.x,pa.y,lobeA,0,TAU);ctx.arc(pb.x,pb.y,lobeB,0,TAU);ctx.fill();ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.quadraticCurveTo((pa.x+pb.x)/2,(pa.y+pb.y)/2,pb.x,pb.y);ctx.stroke();ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const t=tri();ctx.strokeStyle='#eee';ctx.lineWidth=Math.max(1,Math.min(W,H)/700);ctx.beginPath();t.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.fillStyle='#666';ctx.font=`${Math.max(8,Math.min(W,H)/100)}px Space Mono`;ctx.fillText('MY WORK',t[0].x-28,t[0].y-34);ctx.fillText('THINGS I FIND INTERESTING',t[1].x-18,t[1].y+42);ctx.fillText("WORK OF OTHERS I WISH I'D MADE",t[2].x-130,t[2].y+42);for(const n of nodes){let tx=n.home.x,ty=n.home.y;if(selected&&n!==selected){const rel=relation(selected,n);if(rel){tx=selected.x+(n.home.x-selected.x)*(1-rel.strength*.95);ty=selected.y+(n.home.y-selected.y)*(1-rel.strength*.95)}}n.vx=(n.vx+(tx-n.x)*.055)*.84;n.vy=(n.vy+(ty-n.y)*.055)*.84;n.x+=n.vx;n.y+=n.vy;constrain(n)}separateRelated();separateAll();drawFusion();for(const n of nodes){const p={x:n.x*W,y:n.y*H};blob(n,p.x,p.y,radiusOf(n))}requestAnimationFrame(draw)}
function hit(x,y){return nodes.find(n=>{const p={x:n.x*W,y:n.y*H};return Math.hypot(x-p.x,y-p.y)<radiusOf(n)})}
canvas.addEventListener('pointermove',e=>{if(!drag)return;drag.node.x+=(e.clientX-drag.lastX)/W;drag.node.y+=(e.clientY-drag.lastY)/H;drag.node.vx=drag.node.vy=0;constrain(drag.node);drag.node.home={x:drag.node.x,y:drag.node.y};drag.lastX=e.clientX;drag.lastY=e.clientY;drag.moved||=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>7});canvas.addEventListener('pointerdown',e=>{const n=hit(e.clientX,e.clientY);if(!n){select(null);return}drag={node:n,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>{if(!drag)return;const d=drag;drag=null;if(!d.moved)selected===d.node?openNode(d.node):select(d.node)});canvas.addEventListener('pointercancel',()=>drag=null);addEventListener('keydown',e=>{if(e.key==='Escape')select(null)});addEventListener('resize',resize);resize();draw();
