import './style.css';
import { nodes, relations } from './data.js';

const canvas = document.querySelector('#triangle'), ctx = canvas.getContext('2d');
const detail = document.querySelector('#detail'), modeButton = document.querySelector('#mode'), TAU = Math.PI * 2;
const images = new Map(), field = document.createElement('canvas'), fctx = field.getContext('2d');
let selected = null, hovered = null, drag = null, W, H, dpr, fw, fh, mode = 'night';
modeButton.addEventListener('click', () => { mode = mode === 'night' ? 'day' : 'night'; document.body.classList.toggle('day', mode === 'day'); modeButton.textContent = mode === 'day' ? 'NIGHT MODE' : 'DAY MODE'; });

const asset = path => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;
for (const n of nodes) { n.home = { x: n.x, y: n.y }; n.vx = 0; n.vy = 0; const image = new Image(); image.onload = () => images.set(n.id, image); image.src = asset(n.image); }
function resize() { dpr = devicePixelRatio || 1; W = innerWidth; H = innerHeight; canvas.width = W * dpr; canvas.height = H * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); fw = Math.floor(W); fh = Math.floor(H); field.width = fw; field.height = fh; fctx.imageSmoothingEnabled = true; }
function pos(n) { return { x: n.x * W, y: n.y * H }; }
function radiusOf(n) { return Math.max(38, n.radius * Math.min(W, H) / 900) * (n === selected ? 1.12 : 1); }
function keepInside(n) { const marginX = radiusOf(n) / W, marginY = radiusOf(n) / H, top = .15 + marginY, bottom = .78 - marginY; n.y = Math.max(top, Math.min(bottom, n.y)); let t = (n.y - .15) / .63, left = .5 + (.18 - .5) * t + marginX, right = .5 + (.82 - .5) * t - marginX; if (left > right) { n.y = Math.min(n.y, .64); t = (n.y - .15) / .63; left = .5 + (.18 - .5) * t + marginX; right = .5 + (.82 - .5) * t - marginX; } n.x = Math.max(left, Math.min(right, n.x)); }
function separateNodes() { for (let pass = 0; pass < 2; pass++) for (let i = 0; i < nodes.length; i++) for (let j = i + 1; j < nodes.length; j++) { const a = nodes[i], b = nodes[j], dx = (b.x - a.x) * W, dy = (b.y - a.y) * H, d = Math.hypot(dx, dy) || 1, min = radiusOf(a) + radiusOf(b) + 12; if (d >= min) continue; const push = (min - d) / d / 2, px = dx * push / W, py = dy * push / H; if (a !== drag?.node) { a.x -= px; a.y -= py; } if (b !== drag?.node) { b.x += px; b.y += py; } keepInside(a); keepInside(b); a.home.x = a.x; a.home.y = a.y; b.home.x = b.x; b.home.y = b.y; } }
function relation(a, b) { return relations.find(r => (r.source === a.id && r.target === b.id) || (r.source === b.id && r.target === a.id)); }
function openNode(n) { if (n.url) window.open(n.url, '_blank', 'noopener,noreferrer'); ; }
function select(n) { selected = n; if (!n) { detail.className = ''; detail.innerHTML = ''; return; } detail.className = 'visible'; detail.innerHTML = `<span>${n.categoryLabel}${n.newSinceIED ? ' · NEW SINCE IED' : ''}</span><h2>${n.title}</h2><div>${n.keywords.join(' · ')}</div><p>${n.reflection || n.descriptionEN}</p><small>${n.reflectionCN || n.descriptionCN || '关于身体、系统与能动性的实践观察。'}</small><button class="open">OPEN ↗</button>`; detail.querySelector('.open').onclick = () => openNode(n); }
function blobCircle(n, x, y, r) { const image = images.get(n.id); ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, TAU); ctx.clip(); if (image) { const scale = Math.max(r * 2 / image.width, r * 2 / image.height); ctx.drawImage(image, x - image.width * scale / 2, y - image.height * scale / 2, image.width * scale, image.height * scale); ctx.fillStyle = 'rgba(0,0,0,.18)'; ctx.fillRect(x - r, y - r, r * 2, r * 2); } else { ctx.fillStyle = '#181818'; ctx.fillRect(x - r, y - r, r * 2, r * 2); ctx.fillStyle = '#777'; ctx.font = '8px Space Mono'; ctx.textAlign = 'center'; ctx.fillText('IMAGE', x, y + 3); } const shade = ctx.createRadialGradient(x-r*.35,y-r*.4,r*.08,x,y,r*1.2); shade.addColorStop(0,'rgba(255,255,255,.14)'); shade.addColorStop(.55,'rgba(255,255,255,0)'); shade.addColorStop(1,'rgba(0,0,0,.28)'); ctx.fillStyle=shade; ctx.fillRect(x-r,y-r,r*2,r*2); ctx.restore(); ctx.strokeStyle = n === selected ? '#fff' : 'rgba(255,255,255,.45)'; ctx.lineWidth = n === selected ? 1.5 : 1; ctx.beginPath(); ctx.arc(x, y, r, 0, TAU); ctx.stroke(); }
function drawRelationCurves(){if(!selected)return;const a=pos(selected);for(const n of nodes){if(n===selected||!relation(selected,n))continue;const b=pos(n),mx=(a.x+b.x)/2,my=(a.y+b.y)/2-Math.max(28,Math.min(W,H)*.06);ctx.save();ctx.setLineDash([4,7]);ctx.strokeStyle='rgba(241,241,239,.52)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(mx,my,b.x,b.y);ctx.stroke();ctx.restore();}}
function drawLiquidLayer(){if(!selected)return;const data=fctx.createImageData(fw,fh),px=data.data,linked=[selected,...nodes.filter(n=>n!==selected&&relation(selected,n))];for(let y=0;y<fh;y++)for(let x=0;x<fw;x++){let value=0;for(const n of linked){const p=pos(n),r=radiusOf(n),dx=x-p.x,dy=y-p.y;value+=r*r/Math.max(1,dx*dx+dy*dy)}if(value>.92){const i=(y*fw+x)*4;px[i]=px[i+1]=px[i+2]=mode==='day'?0:235;px[i+3]=Math.min(220,150+value*70)}}fctx.putImageData(data,0,0);ctx.save();ctx.globalAlpha=.78;ctx.drawImage(field,0,0,W,H);ctx.restore();}
// Genuine scalar-field metaballs: the bridge appears only as related circles approach.
function draw() { ctx.clearRect(0, 0, W, H); const tri = [{ x: .5, y: .15 }, { x: .18, y: .78 }, { x: .82, y: .78 }].map(p => ({ x: p.x * W, y: p.y * H })); ctx.strokeStyle = '#eee'; ctx.lineWidth = Math.max(1, Math.min(W, H) / 700); ctx.beginPath(); tri.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.stroke(); ctx.fillStyle = '#666'; ctx.font = `${Math.max(8, Math.min(W, H) / 100)}px Space Mono`; ctx.fillText('MY WORK', tri[0].x - 28, tri[0].y - 34); ctx.fillText('THINGS I FIND INTERESTING', tri[1].x - 18, tri[1].y + 42); ctx.fillText("WORK OF OTHERS I WISH I'D MADE", tri[2].x - 130, tri[2].y + 42);
  for (const n of nodes) { let tx = n.home.x, ty = n.home.y; if (selected && n !== selected) { const r = relation(selected, n); if (r) { tx = selected.x + (n.home.x - selected.x) * (1 - r.strength * .68); ty = selected.y + (n.home.y - selected.y) * (1 - r.strength * .68); } } n.vx = (n.vx + (tx - n.x)  * .045) * .88; n.vy = (n.vy + (ty - n.y)  * .045) * .88; n.x += n.vx; n.y += n.vy; keepInside(n); } separateNodes(); drawLiquidLayer(); for (const n of nodes) { const p = pos(n), radius = radiusOf(n); blobCircle(n, p.x, p.y, radius);  } requestAnimationFrame(draw); }
function hit(x, y) { return nodes.find(n => { const p = pos(n), r = radiusOf(n); return Math.hypot(x - p.x, y - p.y) < r; }); }
canvas.addEventListener('pointermove', e => { hovered = hit(e.clientX, e.clientY); if (!drag) return; drag.node.x += (e.clientX - drag.lastX) / W; drag.node.y += (e.clientY - drag.lastY) / H; drag.node.vx = drag.node.vy = 0; keepInside(drag.node); drag.node.home.x = drag.node.x; drag.node.home.y = drag.node.y; drag.lastX = e.clientX; drag.lastY = e.clientY; if (Math.hypot(e.clientX - drag.startX, e.clientY - drag.startY) > 7) drag.moved = true; });
canvas.addEventListener('pointerdown', e => { const n = hit(e.clientX, e.clientY); if (!n) { select(null); return; } drag = { node: n, startX: e.clientX, startY: e.clientY, lastX: e.clientX, lastY: e.clientY, moved: false }; canvas.setPointerCapture(e.pointerId); });
canvas.addEventListener('pointerup', e => { if (!drag) return; const { node, moved } = drag; drag = null; if (!moved) { if (selected === node) openNode(node); else select(node); } }); canvas.addEventListener('pointercancel', () => drag = null);
addEventListener('keydown', e => { if (e.key === 'Escape') { select(null); } }); addEventListener('resize', resize); resize(); draw();
